// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaDandoOnda.Models;

namespace TaDandoOnda.Migrations
{
    [DbContext(typeof(TaDandoOndaContext))]
    [Migration("20200711155309_ThirdCreate")]
    partial class ThirdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaDandoOnda.Models.Manobra", b =>
                {
                    b.Property<int>("ManobraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aérea")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SurfistaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDeOnda")
                        .HasColumnType("int");

                    b.HasKey("ManobraId");

                    b.HasIndex("SurfistaId");

                    b.ToTable("Manobras");
                });

            modelBuilder.Entity("TaDandoOnda.Models.Surfista", b =>
                {
                    b.Property<int>("SurfistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SurfistaId");

                    b.ToTable("Surfistas");
                });

            modelBuilder.Entity("TaDandoOnda.Models.Manobra", b =>
                {
                    b.HasOne("TaDandoOnda.Models.Surfista", "Surfista")
                        .WithMany("Manobras")
                        .HasForeignKey("SurfistaId");
                });
#pragma warning restore 612, 618
        }
    }
}
